name: laravel_pusher_plus
description: Pusher client that supports laravel echo in flutter projects. Supports Null satefy
version: 1.0.0
homepage: "https://github.com/tonywaar/laravel_pusher_plus"

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  json_serializable: ^6.7.1
  build_runner: ^2.0.6

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: dev.tonywaar.laravel_pusher_plus
        pluginClass: LaravelPusherPlusPlugin
      ios:
        pluginClass: LaravelPusherPlusPlugin
